#!/usr/bin/env bash
SOURCED_ROOKCEPH_HEALTH=yes


rookceph_healthcheck()
{
    kubectl -n rook-ceph \
	    exec $(kubectl -n rook-ceph get pod -l "app=rook-ceph-tools" -o jsonpath='{.items[0].metadata.name}') \
	    -- \
	    ceph status \
	| egrep -e 'health: HEALTH_OK|health: HEALTH_WARN' \
	       >/dev/null 2>&1
}
