#!/usr/bin/env bash
# script that configures the networking + IP for raspberry
# running kubernetes over rocky linux
set -euxo pipefail
host=$1
ip=$2
if [[ ! -f /boot/cmdline.txt_pre_config ]]; then
    cp /boot/cmdline.txt /boot/cmdline.txt_pre_config
fi
cat > /boot/cmdline.txt <<EOF
# check the other parameters here:
# - https://www.kernel.org/doc/html/v4.14/admin-guide/kernel-parameters.html
# - https://kr15h.github.io/RPi-Setup/index.html
console=ttyAMA0,115200 console=tty1 root=/dev/sda3 rootfstype=ext4 elevator=deadline rootwait cgroup_memory=1 cgroup_enable=memory ip=${ip}::17.17.0.1:255.255.0.0
EOF
cat /boot/cmdline.txt

cat > /etc/sysconfig/network-scripts/ifcfg-eth0 <<EOF
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=none
DEFROUTE=yes
IPV4_FAILURE_FATAL=yes
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=eth0
UUID=$(uuidgen)
DEVICE=eth0
ONBOOT=yes
IPADDR=$ip
PREFIX=16
GATEWAY=17.17.0.1
DNS1=8.8.8.8
DNS2=8.8.4.4
IPV6_PRIVACY=no
EOF
cat /etc/sysconfig/network-scripts/ifcfg-eth0

echo "$host" > /etc/hostname
hostnamectl set-hostname "$host"
hostnamectl

cat > /etc/resolv.conf <<EOF
# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF
cat /etc/resolv.conf
